services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}'

  pgadmin:
    image: dpage/pgadmin4:6.21
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '${PG_ADMIN_PORT_EXTERNAL}:${PG_ADMIN_PORT_INTERNAL}'
    depends_on:
      - db

  api:
    build:
      context: .
    image: realworld-api:local
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT_INTERNAL}/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      TEST_UTILS_TOKEN: ${TEST_UTILS_TOKEN}
      MIN_REQUEST_DELAY_MS: ${MIN_REQUEST_DELAY_MS}
      MAX_REQUEST_DELAY_MS: ${MAX_REQUEST_DELAY_MS}
    depends_on:
      - db
    ports:
      - '${API_PORT_EXTERNAL}:${PORT}'

volumes:
  postgres_data:
  pgadmin_data:
